### PR TITLE
Add base payment provider

### PR DESCRIPTION
**Pull request by bjarnef**
Added a base payment provider for Bambora.

### CODE REVIEW

**Comment by bjarnef** [comment]
@mattbrailsford I have updated this so the alias is `bambora-checkout` and `BamboraCheckoutPaymentProvider`.

**Comment by bjarnef** [comment]
@mattbrailsford while you are looking at the different payment providers, maybe you could have a look at this one as well? 😊😎

**Comment by mattbrailsford** [comment]
I was a bit concerned about renaming the alias of the provider as that would be a breaking change, but it doesn't look like we officially released the Bambora provider so that shouldn't be a problem.

**Comment by bjarnef** [comment]
Yeah, I only renamed the alias because the payment provider wasn't officially released yet 👍

**Pull request merged**
